# Generated by Django 6.0.4 on 2026-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_phone_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('CONF', 'Кондитер'), ('COOK', 'Повар-кондитер'), ('MCONF', 'Главный кондитер')], max_length=30, verbose_name='Роль'),
        ),
    ]
