# Generated by Django 5.2.7 on 2026-05-05 13:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=30)),
                ('selected', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChangedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.ManyToManyField(to='storage.changes')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('contents', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'weight')},
            },
        ),
        migrations.AddField(
            model_name='changes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=10)),
                ('delivery_address', models.CharField(max_length=30)),
                ('payment_type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.employee')),
            ],
            options={
                'unique_together': {('customer', 'creation_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='changes',
            unique_together={('item', 'component', 'selected')},
        ),
        migrations.CreateModel(
            name='ItemsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('changeditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.changeditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order')),
            ],
            options={
                'unique_together': {('order', 'changeditem')},
            },
        ),
    ]
