# Generated by Django 6.0.4 on 2026-05-21 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('NONE', 'Нету'), ('CREAM', 'Крем'), ('KORZH', 'Корж'), ('GLAZE', 'Глазурь'), ('DECOR', 'Украшение')], max_length=30)),
                ('selected', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ChangedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.ManyToManyField(to='storage.changes')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('contents', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='static/uploads/')),
            ],
            options={
                'unique_together': {('name', 'weight')},
            },
        ),
        migrations.AddField(
            model_name='changes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('SELF', 'Самовывоз'), ('DELIVERY', 'Доставка')], max_length=10, null=True)),
                ('delivery_address', models.CharField(max_length=30, null=True)),
                ('payment_type', models.CharField(choices=[('ON_RECEIVE', 'При получении'), ('CARD', 'По карте')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Обрабатывается'), ('IN_BUILDING', 'В готовке'), ('IN_DELIVERY', 'В доставке'), ('RECEIVED', 'Получен'), ('CANCELLED', 'Отменен')], max_length=11, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'unique_together': {('customer', 'creation_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='changes',
            unique_together={('item', 'component', 'selected')},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('changeditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.changeditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order')),
            ],
            options={
                'unique_together': {('order', 'changeditem')},
            },
        ),
    ]
