# Generated by Django 6.0.4 on 2026-04-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('contents', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=30)),
                ('selected', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=10)),
                ('delivery_address', models.CharField(max_length=30)),
                ('payment_type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsInOrder',
            fields=[
                ('pk', models.CompositePrimaryKey('order_id', 'changes_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('changes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.changes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order')),
            ],
        ),
    ]
