# Generated by Django 6.0.4 on 2026-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinorder',
            name='changeditem_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='pk',
            field=models.CompositePrimaryKey('order_id', 'changeditem_id', 'changes_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
