# Generated by Django 5.2.7 on 2026-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changes',
            name='component',
            field=models.CharField(choices=[('NO', 'Нету'), ('CR', 'Крем'), ('KO', 'Корж'), ('GL', 'Глазурь'), ('DE', 'Украшение')], max_length=30),
        ),
    ]
