# Generated by Django 6.0.4 on 2026-05-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_phone_alter_employee_role_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='changeditem',
        ),
        migrations.DeleteModel(
            name='ChangedItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='changeditem',
            field=models.ManyToManyField(to='storage.changes'),
        ),
    ]
