# Generated by Django 6.0.4 on 2026-05-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_orderitem_unique_together_alter_order_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
