# Generated by Django 6.0.4 on 2026-05-29 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_options_alter_employee_options'),
        ('storage', '0003_remove_order_is_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changes',
            options={'verbose_name': 'Изменение', 'verbose_name_plural': 'Изменения'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterField(
            model_name='changes',
            name='component',
            field=models.CharField(choices=[('NONE', 'Нету'), ('CREAM', 'Крем'), ('KORZH', 'Корж'), ('GLAZE', 'Глазурь'), ('DECOR', 'Украшение')], max_length=30, verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='changes',
            name='selected',
            field=models.CharField(max_length=30, verbose_name='Выбранный'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.CharField(max_length=100, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/uploads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=30, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SELF', 'Самовывоз'), ('DELIVERY', 'Доставка')], max_length=10, null=True, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ON_RECEIVE', 'При получении'), ('CARD', 'По карте')], max_length=10, null=True, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Обрабатывается'), ('IN_BUILDING', 'В готовке'), ('IN_DELIVERY', 'В доставке'), ('RECEIVED', 'Получен'), ('CANCELLED', 'Отменен')], max_length=11, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='changeditem',
            field=models.ManyToManyField(to='storage.changes', verbose_name='Изменения'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order', verbose_name='Заказ'),
        ),
    ]
