# Generated by Django 6.0.4 on 2026-05-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_order_is_ordered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsInOrder',
            new_name='OrderItem',
        ),
    ]
