# Generated by Django 6.0.5 on 2026-06-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_options_alter_user_options_and_more'),
        ('storage', '0004_alter_changes_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changes',
            options={'ordering': ['price'], 'verbose_name': 'Изменение', 'verbose_name_plural': 'Изменения'},
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Покупатель'),
        ),
    ]
