# Generated by Django 6.0.4 on 2026-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_rename_itemsinorder_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
