# Generated by Django 6.0.4 on 2026-05-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_order_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changes',
            unique_together=set(),
        ),
    ]
