# Generated by Django 6.0.4 on 2026-05-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_changes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='changes',
            unique_together={('item', 'component', 'selected')},
        ),
    ]
