# Generated by Django 6.0.4 on 2026-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
