# Generated by Django 6.0.4 on 2026-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='component',
            field=models.CharField(choices=[('NONE', 'Нету'), ('CREAM', 'Крем'), ('KORZH', 'Корж'), ('GLAZE', 'Глазурь'), ('DECOR', 'Украшение')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SELF', 'Самовывоз'), ('DELIVERY', 'Доставка')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ON_RECEIVE', 'При получении'), ('CARD', 'По карте')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Обрабатывается'), ('IN_BUILDING', 'В готовке'), ('IN_DELIVERY', 'В доставке'), ('RECEIVED', 'Получен'), ('CANCELLED', 'Отменен')], max_length=11, null=True),
        ),
    ]
